version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: fincheck-nestjs-api
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    ports:
      - "4000:4000"
    restart: always
    networks:
      - fincheck-network
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: fincheck-postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - fincheck-network

networks:
  fincheck-network:
    driver: bridge

volumes:
  postgres-data: