version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fincheck-nestjs-api-prod
    environment:
      DATABASE_URL: ${DATABASE_URL} 
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4000:4000"
    networks:
      - fincheck-network

networks:
  fincheck-network:
    driver: bridge